framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            async:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              # Si ma tache echoue n'essaie pas de reesayer
              retry_strategy:
                   max_retries: 0
            failed: 'doctrine://default?queue_name=failed'
            # failed: 'MESSENGER_TRANSPORT_DSN_FAILED'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # On envoie notre message en utilisant le transport appele "async"
            App\Message\UserNotificationMessage: async
            # 'App\Message\YourMessage': async
