# Development
services:
   # nginx
   web:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

   # php
   # add volumes: - /var/www/html/vendor for auto-generation ./vendor
   # target the alias (given name) in ./php/Dockerfile, recommended for creating multistage
   # ro: that mean (read-only)
   app:
      build:
          dockerfile: ./php/Dockerfile
          #target: app
          target: "${BUILD_TARGET:-app}"
      volumes:
          - ./app:/var/www/html
          - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      environment:
          MYSQL_HOST: db
          MYSQL_PORT: ${MYSQL_PORT}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          REDIS_HOST: cache
          REDIS_PORT: ${REDIS_PORT}
          # See https://xdebug.org/docs/all_settings#mode
          # e.g set default variable without .env
          XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      extra_hosts:
          # Ensure that host.docker.internal is correctly defined on Linux
          - host.docker.internal:host-gateway

   # mysql (https://hub.docker.com/_/mysql/tags)
   # If has not mysql 8.0 use different port e.g: "4306:3306", or by default "3306:3306"
   db:
     image: mysql:8.0
     volumes:
       - mysqldata:/var/lib/mysql
     ports:
       - "4306:3306"
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_USER: user
       MYSQL_PASSWORD: secret
       MYSQL_DATABASE: docker-php

   # redis
   cache:
     image: redis:latest


# defaults
volumes:
  mysqldata: