version: '3.9'

services:
   database:
     container_name: postgres
     image: postgres:13.3-alpine
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 123456
       POSTGRES_HOST_AUTH_METHOD: trust
     ports:
       - "54322:5432"
